import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './redux/Providers'
import Providekro from './v1/1/helper/Provideapi'

const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providekro>
      <Providers>
      <body>{children}</body>
      </Providers>
      </Providekro>
    </html>
  )
}
